### ISSUE TITLE
Chapter 6 solution 1: two questions

### ISSUE THREAD

**Issue by cwnelson88** [kyclark/biofx_python#1]
Dear Ken: from one Perl hack to his better, I cannot thank you enough for this book!

I have two likely trivial questions:

1. At the bottom of p. 142, I had initially tried the following:

`distance += 1 if seq1[i] != seq2[i]`

However, this fails. Would you be willing to help help me understand why this does not work in Python?

2. On p. 142-143, you copy the two sequences into variables rather than using them directly as `args.seq1` and `args.seq2`. Is there a computational or other advantage to doing this? I ask because I am always afraid of making multiple copies of sequences in case they're too long.

Very grateful for this book, and for your help!
Chase

**Comment by kyclark** [comment]
Chase,

Glad you dig the book! As for #1, Python doesn't have Perl's cool post-fix comparisons. You have to write:

```
if seq1[i] != seq2[i]:
    distance += 1
```

Alternately, you could smash this into an if-expression that looks kinda/sorta like Perl:

```
distance += 1 if seq1[i] != seq2[i] else 0
```

As for #2, there's no great advantage over copying those values into new variables. You are welcome to just use `args.seq1` and such if you are worried about memory. This is a very trivial case, but I can understand your concern if you were dealing with extremely large sequences (and lots of them). Generally, I would probably make copies and only concern myself with memory issues if the program seems slow. It might be one of those "you ain't gonna need it" situations when you concern yourself with premature optimization.

**Comment by cwnelson88** [comment]
This makes perfect sense — thanks a ton for the quick and crystal clear help!
