### ISSUE TITLE
wget in fetch_fasta.sh bash script, chapter 11

### ISSUE THREAD

**Issue by singing-scientist** [kyclark/biofx_python#2]
Dear Ken:

When running `./fetch_fasta.sh tests/inputs/1.txt` from inside `/biofx_python/11_mprt/`, four empty FASTA files were being created in the `/fasta/` directory. It's possible I have a different version of `wget`; mine is **iGNU Wget 1.21.1 built on darwin19.6.0**. However, I got it working as follows:

1. Add a ".fasta" suffix to the end of `$URL`, i.e.:

`URL="https://www.uniprot.org/uniprot/${PROT_ID}.fasta"`

2. Change the `-o` to `-O` in the `wget` call, i.e.:

`wget -q -O "$OUT_FILE" "$URL"`

Does that seem correct, or do you think my problem lies elsewhere?

Many thanks!
Chase

**Comment by kyclark** [comment]
Both of those fixes are needed. I also changed https to http just to make it simpler. Pushing this change now. Sorry about that, and thanks for the spot!

**Comment by singing-scientist** [comment]
Awesome! Thanks as always for the lightning-fast help :->
