### ISSUE TITLE
Figure 16-3

### ISSUE THREAD

**Issue by singing-scientist** [kyclark/biofx_python#5]
Greetings! I am wondering if there should be one additional arrow in Figure 16-3, namely an arrow pointing from the second circle to the last circle, and labelled 'a'? The second circle would then have two arrows emanating from it, one labelled 'n' and one labelled 'a'. (It's totally possible I have a misunderstanding due to unfamiliarity with finite state machine diagrams!)

Many thanks,
Chase

**Comment by kyclark** [comment]
Yes, I think you're right.
